#!/bin/bash

if [ ! $1 ]; then
  echo "Must specify a version number"
  exit 1
fi

VERSION=$1
CODE=glz_custom_fields-$VERSION.gz.txt
ARCHIVES=(tgz zip)
FILES=(CHANGELOG.md INSTALL.md $CODE glz_custom_fields)

# prepare plugin code...
#
php glz_custom_fields.php > releases/$CODE

cd releases

# re/package plugin
#
for archive in ${ARCHIVES[*]}
do
  plugin="glz_custom_fields-$VERSION.$archive"
  [ -e $plugin ] && rm $plugin

  case $archive in
  tgz ) echo -e "\nCreating $plugin ..."
    tar zcvf $plugin --exclude="*un~" --exclude="*DS_Store" ${FILES[*]} ;;
  zip ) echo -e "\nCreating $plugin ..."
    zip -r $plugin $CODE ${FILES[*]} -x \*un~ \*DS_Store
  esac
done

# cleanup
rm $CODE
