#!/usr/bin/env bash

if [[ -z "$1" ]]
then
  echo "The first argument must be the version that will be packaged"
  exit 1
fi

version="$1"
export PLUGIN_VERSION="$version"

code="glz_custom_fields-$version"
archives=(tgz zip)
files=(CHANGELOG.md INSTALL.md $code glz_custom_fields)

# prepare plugin code...
php glz_custom_fields.php > "releases/$code" &&
cd releases &&
# re/package plugin
for archive in ${archives[@]}
do
  plugin="glz_custom_fields-$version.$archive"
  if [[ -e $plugin ]]
  then
    rm $plugin
  fi

  case $archive in
    (tgz)
      echo -e "\n----> Creating $plugin"
      tar zcvf $plugin --exclude="*un~" --exclude="*DS_Store" ${files[@]}
    ;;
    (zip)
      echo -e "\n ----> Creating $plugin"
      zip -r $plugin $code ${files[*]} -x \*un~ \*DS_Store
    esac
done &&
# cleanup
rm $code &&
echo -e "\nglz_custom_fields $version successfully packaged\n"

unset PLUGIN_VERSION
